LEXEMA               | TIPO DE TOKEN     | LINHA | COLUNA
------------------------------------------------------------------
program              | KEY_PROGRAM       | 1     | 1
tortura_visual       | ID                | 1     | 14
;                    | SMB_SEM           | 1     | 31
var                  | KEY_VAR           | 1     | 33
x                    | ID                | 2     | 3
:                    | SMB_COLON         | 2     | 4
integer              | KEY_INTEGER       | 2     | 5
;                    | SMB_SEM           | 2     | 12
begin                | KEY_BEGIN         | 2     | 13
x                    | ID                | 2     | 36
:=                   | OP_ASS            | 5     | 3
10                   | LIT_INT           | 5     | 13
;                    | SMB_SEM           | 5     | 15
if                   | KEY_IF            | 8     | 3
x                    | ID                | 8     | 6
>                    | OP_GT             | 8     | 7
0                    | LIT_INT           | 8     | 8
then                 | KEY_THEN          | 8     | 10
begin                | KEY_BEGIN         | 8     | 15
x                    | ID                | 8     | 21
:=                   | OP_ASS            | 8     | 22
x                    | ID                | 8     | 24
+                    | OP_AD             | 8     | 25
1                    | LIT_INT           | 8     | 26
end                  | KEY_END           | 8     | 28
end                  | KEY_END           | 8     | 67
.                    | SMB_DOT           | 8     | 70
